# The folders for all the generatesed files, these should remain unchanged
PATHS:
  POINT_CLOUD_LOCATION: 'point_cloud'
  FILTERED_POINT_CLOUD_LOCATION: 'filtered_point_cloud'
  MESH_LOCATION: 'mesh'
  SCRIPT_LOCATION: 'script'

# The desired file names for output files, avoid using duplicate names.
NAMES:
  POINT_CLOUD_NAME: 'scan_test.xyz'
  FILTERED_POINT_CLOUD_NAME: 'filtered_point_cloud.npy.xyz'
  MESH_NAME: 'filtered_data_mesh.obj'
  SCRIPT_NAME: 'script1.mlx'
  SENSOR_PACKAGE_LOCATIONS_NAME: 'sensor_package_locations.npy'